### ISSUE TITLE
Broke instance components after use reorder

### ISSUE THREAD

**Issue by Kobreros** [mikegowen/figma-reverse-layer-order#1]
After using the plugin, instance components not follow to master.

https://funkyimg.com/i/2WfUN.gif

**Comment by mikegee0101** [comment]
I was able to repro. Will take a look at it this evening. Very odd.

**Comment by mikegee0101** [comment]
This has been fixed! It actually unearthed a more fundamental problem. I've refactored the plugin and should have eliminated an entire class of potential bugs. Good find.
